AllCops:
  TargetRubyVersion: 2.7.1
  Exclude:
  - "**/db/**/*"
  - "**/bin/**/*"
  - "**/node_modules/**/*"
  DisplayCopNames: true
  StyleGuideCopsOnly: false

Style/Encoding:
  Enabled: false
Style/LambdaCall:
  Enabled: false
Style/Documentation:
  Description: Document classes and non-namespace modules.
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Lint/UselessAccessModifier:
  ContextCreatingMethods:
    - class_methods
Layout/LineLength:
  Description: Limit lines to 120 characters.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#80-character-limits
  Enabled: true
  Max: 120
  AllowURI: true
  URISchemes:
  - http
  - https
Style/RegexpLiteral:
  Description: Use %r for regular expressions matching more than `MaxSlashes` '/'
    characters. Use %r only for regular expressions matching more than `MaxSlashes`
    '/' character.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#percent-r
  Enabled: false
Naming/MethodParameterName:
  MinNameLength: 2
  AllowedNames:
    - "_"
Naming/MemoizedInstanceVariableName:
  Enabled: false
Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"
Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
